# Generated by Django 5.2 on 2025-04-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_school_admin', '0002_alter_customuser_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
