# Generated by Django 5.2 on 2025-05-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_school_admin", "0005_alter_adminaction_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="news_photos/")),
                ("header", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
