# Generated by Django 5.2 on 2025-05-23 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_message", "0001_initial"),
        ("common", "0014_remove_customuser_online_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlineStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("online_status", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_online_status",
                        to="common.userprofile",
                    ),
                ),
            ],
        ),
    ]
