# Generated by Django 5.2 on 2025-05-23 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_message", "0002_onlinestatus"),
        ("common", "0014_remove_customuser_online_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlinestatus",
            name="last_seen",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="onlinestatus",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.userprofile"
            ),
        ),
    ]
