# Generated by Django 5.2 on 2025-06-10 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_teacher", "0004_quickquiz_answered_quickquiz_is_correct_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quickquiz",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_quizzes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
