# Generated by Django 5.2 on 2025-06-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a_teacher", "0005_quickquiz_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quickquiz",
            name="student",
        ),
    ]
