# Generated by Django 5.2 on 2025-05-10 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='student',
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'role': 'student'}, related_name='classroom_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='class_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='common.class'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='room_teacher',
            field=models.OneToOneField(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='class_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_subjects', to='common.classroom'),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='teaching_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('class_room', 'subject')},
        ),
    ]
