# Generated by Django 5.2 on 2025-05-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitycategory",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Percentage weight (e.g. 25.00 for 25%)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
