# Generated by Django 5.2 on 2025-05-30 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_activitycategory_weight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="activity_type",
        ),
    ]
