# Generated by Django 5.2 on 2025-05-11 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_classroom_student_classroom_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_set', to='common.class'),
        ),
    ]
