# Generated by Django 5.2.4 on 2025-10-04 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_activity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='room_teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.userprofile'),
        ),
    ]
