# Generated by Django 5.2 on 2025-05-12 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_classroom_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('test', 'Test'), ('quiz', 'Quiz'), ('homework', 'Homework')], max_length=20)),
                ('activity_name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='common.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='common.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities_created', to='common.userprofile')),
            ],
            options={
                'ordering': ['-date_created'],
                'unique_together': {('class_room', 'subject', 'activity_name')},
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='common.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks_received', to='common.userprofile')),
            ],
            options={
                'ordering': ['activity', 'student'],
                'unique_together': {('activity', 'student')},
            },
        ),
        migrations.DeleteModel(
            name='MarkList',
        ),
    ]
