# Generated by Django 5.2.4 on 2025-10-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_classroom_room_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='classroom_students', to='common.userprofile'),
        ),
    ]
