# Generated by Django 5.2 on 2025-05-09 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_class_subject_classroom_marklist_classsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='room_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classroom_teachers', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
