# Generated by Django 5.2.4 on 2025-10-04 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_classroom_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='room_teacher',
            field=models.OneToOneField(blank=True, limit_choices_to={'user__role': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.userprofile'),
        ),
    ]
