# Generated by Django 5.2 on 2025-05-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "common",
            "0006_alter_message_options_rename_content_message_message_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
