# Generated by Django 5.2 on 2025-05-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_delete_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="online_status",
            field=models.BooleanField(default=False),
        ),
    ]
