# Generated by Django 5.2 on 2025-05-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_userprofile_online_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="is_graded",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subject_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
