# Generated by Django 5.2 on 2025-05-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_subject_is_graded_alter_subject_subject_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="online_status",
        ),
        migrations.AddField(
            model_name="customuser",
            name="online_status",
            field=models.BooleanField(default=False),
        ),
    ]
