# Generated by Django 5.2 on 2025-05-19 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="room_teacher",
            field=models.OneToOneField(
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="common.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="students",
            field=models.ManyToManyField(
                limit_choices_to={"role": "student"},
                related_name="classroom_students",
                to="common.userprofile",
            ),
        ),
    ]
