# Generated by Django 5.2 on 2025-05-23 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0013_alter_userprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="online_status",
        ),
        migrations.AlterField(
            model_name="classroom",
            name="class_name",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classroom_set",
                to="common.class",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="room_teacher",
            field=models.OneToOneField(
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="classsubject",
            name="class_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_subjects",
                to="common.classroom",
            ),
        ),
        migrations.AlterField(
            model_name="classsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_classes",
                to="common.subject",
            ),
        ),
        migrations.AlterField(
            model_name="classsubject",
            name="teacher",
            field=models.ForeignKey(
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_subjects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
