# Generated by Django 5.2 on 2025-05-24 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0014_remove_customuser_online_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="class_name",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classroom_set",
                to="common.class",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="students",
            field=models.ManyToManyField(
                limit_choices_to={"role": "student"},
                null=True,
                related_name="classroom_students",
                to="common.userprofile",
            ),
        ),
    ]
