# Generated by Django 5.2 on 2025-05-24 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0015_alter_classroom_class_name_alter_classroom_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="class_name",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classroom_set",
                to="common.class",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="room_teacher",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "student"},
                null=True,
                related_name="classroom_students",
                to="common.userprofile",
            ),
        ),
    ]
