# Generated by Django 5.2 on 2025-05-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0018_alter_conduct_conduct_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="description",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
