# Generated by Django 5.2 on 2025-05-27 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0019_material_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="class_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.class",
            ),
        ),
    ]
